// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD1qgJ6V2M5rGf3F552_C-KPWHUv36LSY',
    appId: '1:949150315483:web:3b1efc8577334a74236dfe',
    messagingSenderId: '949150315483',
    projectId: 'ecommerce-b2af9',
    authDomain: 'ecommerce-b2af9.firebaseapp.com',
    storageBucket: 'ecommerce-b2af9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP1oxF9elVNuYoQ2IZlfF29p-8Ryc-Kpk',
    appId: '1:949150315483:android:979e661df5e24c78236dfe',
    messagingSenderId: '949150315483',
    projectId: 'ecommerce-b2af9',
    storageBucket: 'ecommerce-b2af9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL_ulp6u_4aKGO7PpdSRo9vpNAixs-xxY',
    appId: '1:949150315483:ios:d55e006b3492c391236dfe',
    messagingSenderId: '949150315483',
    projectId: 'ecommerce-b2af9',
    storageBucket: 'ecommerce-b2af9.appspot.com',
    iosClientId: '949150315483-e8na4u4fn4rd88mkld78rfi3trub9h55.apps.googleusercontent.com',
    iosBundleId: 'com.engmaslmadeveloper.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL_ulp6u_4aKGO7PpdSRo9vpNAixs-xxY',
    appId: '1:949150315483:ios:b5137a0a9b40c845236dfe',
    messagingSenderId: '949150315483',
    projectId: 'ecommerce-b2af9',
    storageBucket: 'ecommerce-b2af9.appspot.com',
    iosClientId: '949150315483-5188pama30ve77v5hvkv52cphjqlfhed.apps.googleusercontent.com',
    iosBundleId: 'com.engmaslmadeveloper.ecommerceApp.RunnerTests',
  );
}
